// 前回のレッスンと同じ内容のためコメントは割愛
var abi = /* abi generated by the compiler */
var ZombieFeedingContract = web3.eth.contract(abi)
var contractAddress = /* our contract address on Ethereum after deploying */
var ZombieFeeding = ZombieFeedingContract.at(contractAddress)

// ゾンビのIDと捕食したい子猫のIDをすでに持っていると仮定する
let zombieId = 1;
let kittyId = 1;

// CryptoKitties APIのエンドポイントに特定のKittyのIDを追加する
let apiUrl = "https://api.cryptokitties.co/kitties/" + kittyId

// APIリクエストを送信する
$.get(apiUrl, function(data) {
  let imgUrl = data.image_url
})

// ユーザーが子猫をクリックしたときにイベント発火させる
$(".kittyImage").click(function(e) {
  ZombieFeeding.feedOnKitty(zombieId, kittyId)
})

// コントラクトのNewZombieイベントを表示させる
ZombieFactory.NewZombie(function(error, result) {
  if (error) return
  generateZombie(result.zombieId, result.name, result.dna)
})