// スマートコントラクトにアクセスするために、ABIをどう使うかを指定する
var abi = /* abi generated by the compiler */

// 上記で指定したABIをもとに、スマートコントラクトのためのオブジェクトを作成する
var zombieFactoryContract = web3.eth.contract(abi)
var contractAddress = /* our contract address on Ethereum after deploying */

// インスタンスを作成する。スマートコントラクトがデプロイされているイーサリアムアドレスを指定する
var ZombieFactory = ZombieFactoryContract.at(contractAddress)

// クリックイベント
$("#ourButton").click(function(e) {
    var name = $("#nameInput").val()
    ZombieFactory.createRandomZombie(name)
})

// 新しいゾンビを生成する
var  event = ZombieFactory.NewZombie(function(error, result) {
    if (error) return
    generateZombie(result.zombieId, result.name, result.dna)
})

function generateZombie(id, name, dna) {
    // ランダムなDNAを文字列に変換する
    let dnaStr = String(dna)

    // DNAの文字列が16桁になるよう、足りない桁分を0で埋める
    while (dnaStr.length < 16)
        dbaStr = "0" + dnaStr

        let zombieDetails = {
            headChoice: dnaStr.substring(0, 2) % 7 +1,
            // 11種類の目から選ぶ
            eyeChoice: dnaStr.substring(2, 4) % 11 + 1,
            // 6種類のシャツから選ばせる
            shirtChoice: dnaStr.substring(4, 6) % 6 + 1,
            // 色相Hueで色を指定する
            skinColorChoice: parseInt(dnaStr.substring(6, 8) / 100 * 360),
            eyeColorChoice: parseInt(dnaStr.substring(8, 10) / 100 * 360),
            clothesColorChoice: parseInt(dnaStr.substring(10, 12) / 100 * 360),
            zombieName: name,
            zombieDescription: "A Level 1 CryptoZombie",
        }
    // 生成されたゾンビの情報を返す
    return zombieDetails
}